# Generated by Django 5.1.5 on 2025-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('user_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='posts',
            field=models.ManyToManyField(blank=True, to='user_posts.postmodel'),
        ),
    ]
